name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Install deps
        run: yarn

      - name: Build docs
        run: yarn docs:build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:docs
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
